// source: client.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var protos_pb = require('./protos_pb.js');
goog.object.extend(proto, protos_pb);
var service$activation_pb = require('./service-activation_pb.js');
goog.object.extend(proto, service$activation_pb);
var user$events_pb = require('./user-events_pb.js');
goog.object.extend(proto, user$events_pb);
var vehicle$commands_pb = require('./vehicle-commands_pb.js');
goog.object.extend(proto, vehicle$commands_pb);
var vehicle$events_pb = require('./vehicle-events_pb.js');
goog.object.extend(proto, vehicle$events_pb);
var vehicleapi_pb = require('./vehicleapi_pb.js');
goog.object.extend(proto, vehicleapi_pb);
goog.exportSymbol('proto.proto.ClientMessage', null, global);
goog.exportSymbol('proto.proto.ClientMessage.MsgCase', null, global);
goog.exportSymbol('proto.proto.Logout', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.ClientMessage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.proto.ClientMessage.oneofGroups_);
};
goog.inherits(proto.proto.ClientMessage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.ClientMessage.displayName = 'proto.proto.ClientMessage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.Logout = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.proto.Logout, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.Logout.displayName = 'proto.proto.Logout';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.proto.ClientMessage.oneofGroups_ = [[2,3,4,6,7,9,13,10,11,12,14,15,16,17,18,19,20,21,22,23,26]];

/**
 * @enum {number}
 */
proto.proto.ClientMessage.MsgCase = {
  MSG_NOT_SET: 0,
  UNSUBSCRIBEREQUEST: 2,
  COMMANDREQUEST: 3,
  TRACKING_EVENT: 4,
  PING_INTERVAL: 6,
  ACKNOWLEDGE_VEP_REQUEST: 7,
  ACKNOWLEDGE_SERVICE_STATUS_UPDATES_BY_VIN: 9,
  ACKNOWLEDGE_SERVICE_STATUS_UPDATE: 13,
  ACKNOWLEDGE_USER_DATA_UPDATE: 10,
  ACKNOWLEDGE_USER_PICTURE_UPDATE: 11,
  ACKNOWLEDGE_USER_PIN_UPDATE: 12,
  UPDATE_USER_JWT_REQUEST: 14,
  ACKNOWLEDGE_USER_VEHICLE_AUTH_CHANGED_UPDATE: 15,
  ACKNOWLEDGE_ABILITY_TO_GET_VEHICLE_MASTER_DATA_FROM_REST_API: 16,
  ACKNOWLEDGE_VEHICLE_UPDATED: 17,
  ACKNOWLEDGE_PREFERRED_DEALER_CHANGE: 18,
  ACKNOWLEDGE_APPTWIN_COMMAND_STATUS_UPDATE_BY_VIN: 19,
  LOGOUT: 20,
  APPTWIN_PENDING_COMMANDS_RESPONSE: 21,
  ACKNOWLEDGE_VEP_UPDATES_BY_VIN: 22,
  ACKNOWLEDGE_ASSIGNED_VEHICLES: 23,
  ACKNOWLEDGE_DATA_CHANGE_EVENT: 26
};

/**
 * @return {proto.proto.ClientMessage.MsgCase}
 */
proto.proto.ClientMessage.prototype.getMsgCase = function() {
  return /** @type {proto.proto.ClientMessage.MsgCase} */(jspb.Message.computeOneofCase(this, proto.proto.ClientMessage.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.ClientMessage.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.ClientMessage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.ClientMessage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.ClientMessage.toObject = function(includeInstance, msg) {
  var f, obj = {
trackingId: jspb.Message.getFieldWithDefault(msg, 5, ""),
unsubscriberequest: (f = msg.getUnsubscriberequest()) && protos_pb.UnsubscribeRequest.toObject(includeInstance, f),
commandrequest: (f = msg.getCommandrequest()) && vehicle$commands_pb.CommandRequest.toObject(includeInstance, f),
trackingEvent: (f = msg.getTrackingEvent()) && vehicle$events_pb.TrackingEvent.toObject(includeInstance, f),
pingInterval: (f = msg.getPingInterval()) && vehicle$events_pb.ConfigurePingInterval.toObject(includeInstance, f),
acknowledgeVepRequest: (f = msg.getAcknowledgeVepRequest()) && vehicle$events_pb.AcknowledgeVEPRequest.toObject(includeInstance, f),
acknowledgeServiceStatusUpdatesByVin: (f = msg.getAcknowledgeServiceStatusUpdatesByVin()) && service$activation_pb.AcknowledgeServiceStatusUpdatesByVIN.toObject(includeInstance, f),
acknowledgeServiceStatusUpdate: (f = msg.getAcknowledgeServiceStatusUpdate()) && service$activation_pb.AcknowledgeServiceStatusUpdate.toObject(includeInstance, f),
acknowledgeUserDataUpdate: (f = msg.getAcknowledgeUserDataUpdate()) && user$events_pb.AcknowledgeUserDataUpdate.toObject(includeInstance, f),
acknowledgeUserPictureUpdate: (f = msg.getAcknowledgeUserPictureUpdate()) && user$events_pb.AcknowledgeUserPictureUpdate.toObject(includeInstance, f),
acknowledgeUserPinUpdate: (f = msg.getAcknowledgeUserPinUpdate()) && user$events_pb.AcknowledgeUserPINUpdate.toObject(includeInstance, f),
updateUserJwtRequest: (f = msg.getUpdateUserJwtRequest()) && user$events_pb.UpdateUserJWTRequest.toObject(includeInstance, f),
acknowledgeUserVehicleAuthChangedUpdate: (f = msg.getAcknowledgeUserVehicleAuthChangedUpdate()) && user$events_pb.AcknowledgeUserVehicleAuthChangedUpdate.toObject(includeInstance, f),
acknowledgeAbilityToGetVehicleMasterDataFromRestApi: (f = msg.getAcknowledgeAbilityToGetVehicleMasterDataFromRestApi()) && user$events_pb.AcknowledgeAbilityToGetVehicleMasterDataFromRestAPI.toObject(includeInstance, f),
acknowledgeVehicleUpdated: (f = msg.getAcknowledgeVehicleUpdated()) && vehicle$events_pb.AcknowledgeVehicleUpdated.toObject(includeInstance, f),
acknowledgePreferredDealerChange: (f = msg.getAcknowledgePreferredDealerChange()) && vehicle$events_pb.AcknowledgePreferredDealerChange.toObject(includeInstance, f),
acknowledgeApptwinCommandStatusUpdateByVin: (f = msg.getAcknowledgeApptwinCommandStatusUpdateByVin()) && vehicleapi_pb.AcknowledgeAppTwinCommandStatusUpdatesByVIN.toObject(includeInstance, f),
logout: (f = msg.getLogout()) && proto.proto.Logout.toObject(includeInstance, f),
apptwinPendingCommandsResponse: (f = msg.getApptwinPendingCommandsResponse()) && vehicleapi_pb.AppTwinPendingCommandsResponse.toObject(includeInstance, f),
acknowledgeVepUpdatesByVin: (f = msg.getAcknowledgeVepUpdatesByVin()) && vehicle$events_pb.AcknowledgeVEPUpdatesByVIN.toObject(includeInstance, f),
acknowledgeAssignedVehicles: (f = msg.getAcknowledgeAssignedVehicles()) && protos_pb.AcknowledgeAssignedVehicles.toObject(includeInstance, f),
acknowledgeDataChangeEvent: (f = msg.getAcknowledgeDataChangeEvent()) && vehicle$events_pb.AcknowledgeDataChangeEvent.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.ClientMessage}
 */
proto.proto.ClientMessage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.ClientMessage;
  return proto.proto.ClientMessage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.ClientMessage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.ClientMessage}
 */
proto.proto.ClientMessage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrackingId(value);
      break;
    case 2:
      var value = new protos_pb.UnsubscribeRequest;
      reader.readMessage(value,protos_pb.UnsubscribeRequest.deserializeBinaryFromReader);
      msg.setUnsubscriberequest(value);
      break;
    case 3:
      var value = new vehicle$commands_pb.CommandRequest;
      reader.readMessage(value,vehicle$commands_pb.CommandRequest.deserializeBinaryFromReader);
      msg.setCommandrequest(value);
      break;
    case 4:
      var value = new vehicle$events_pb.TrackingEvent;
      reader.readMessage(value,vehicle$events_pb.TrackingEvent.deserializeBinaryFromReader);
      msg.setTrackingEvent(value);
      break;
    case 6:
      var value = new vehicle$events_pb.ConfigurePingInterval;
      reader.readMessage(value,vehicle$events_pb.ConfigurePingInterval.deserializeBinaryFromReader);
      msg.setPingInterval(value);
      break;
    case 7:
      var value = new vehicle$events_pb.AcknowledgeVEPRequest;
      reader.readMessage(value,vehicle$events_pb.AcknowledgeVEPRequest.deserializeBinaryFromReader);
      msg.setAcknowledgeVepRequest(value);
      break;
    case 9:
      var value = new service$activation_pb.AcknowledgeServiceStatusUpdatesByVIN;
      reader.readMessage(value,service$activation_pb.AcknowledgeServiceStatusUpdatesByVIN.deserializeBinaryFromReader);
      msg.setAcknowledgeServiceStatusUpdatesByVin(value);
      break;
    case 13:
      var value = new service$activation_pb.AcknowledgeServiceStatusUpdate;
      reader.readMessage(value,service$activation_pb.AcknowledgeServiceStatusUpdate.deserializeBinaryFromReader);
      msg.setAcknowledgeServiceStatusUpdate(value);
      break;
    case 10:
      var value = new user$events_pb.AcknowledgeUserDataUpdate;
      reader.readMessage(value,user$events_pb.AcknowledgeUserDataUpdate.deserializeBinaryFromReader);
      msg.setAcknowledgeUserDataUpdate(value);
      break;
    case 11:
      var value = new user$events_pb.AcknowledgeUserPictureUpdate;
      reader.readMessage(value,user$events_pb.AcknowledgeUserPictureUpdate.deserializeBinaryFromReader);
      msg.setAcknowledgeUserPictureUpdate(value);
      break;
    case 12:
      var value = new user$events_pb.AcknowledgeUserPINUpdate;
      reader.readMessage(value,user$events_pb.AcknowledgeUserPINUpdate.deserializeBinaryFromReader);
      msg.setAcknowledgeUserPinUpdate(value);
      break;
    case 14:
      var value = new user$events_pb.UpdateUserJWTRequest;
      reader.readMessage(value,user$events_pb.UpdateUserJWTRequest.deserializeBinaryFromReader);
      msg.setUpdateUserJwtRequest(value);
      break;
    case 15:
      var value = new user$events_pb.AcknowledgeUserVehicleAuthChangedUpdate;
      reader.readMessage(value,user$events_pb.AcknowledgeUserVehicleAuthChangedUpdate.deserializeBinaryFromReader);
      msg.setAcknowledgeUserVehicleAuthChangedUpdate(value);
      break;
    case 16:
      var value = new user$events_pb.AcknowledgeAbilityToGetVehicleMasterDataFromRestAPI;
      reader.readMessage(value,user$events_pb.AcknowledgeAbilityToGetVehicleMasterDataFromRestAPI.deserializeBinaryFromReader);
      msg.setAcknowledgeAbilityToGetVehicleMasterDataFromRestApi(value);
      break;
    case 17:
      var value = new vehicle$events_pb.AcknowledgeVehicleUpdated;
      reader.readMessage(value,vehicle$events_pb.AcknowledgeVehicleUpdated.deserializeBinaryFromReader);
      msg.setAcknowledgeVehicleUpdated(value);
      break;
    case 18:
      var value = new vehicle$events_pb.AcknowledgePreferredDealerChange;
      reader.readMessage(value,vehicle$events_pb.AcknowledgePreferredDealerChange.deserializeBinaryFromReader);
      msg.setAcknowledgePreferredDealerChange(value);
      break;
    case 19:
      var value = new vehicleapi_pb.AcknowledgeAppTwinCommandStatusUpdatesByVIN;
      reader.readMessage(value,vehicleapi_pb.AcknowledgeAppTwinCommandStatusUpdatesByVIN.deserializeBinaryFromReader);
      msg.setAcknowledgeApptwinCommandStatusUpdateByVin(value);
      break;
    case 20:
      var value = new proto.proto.Logout;
      reader.readMessage(value,proto.proto.Logout.deserializeBinaryFromReader);
      msg.setLogout(value);
      break;
    case 21:
      var value = new vehicleapi_pb.AppTwinPendingCommandsResponse;
      reader.readMessage(value,vehicleapi_pb.AppTwinPendingCommandsResponse.deserializeBinaryFromReader);
      msg.setApptwinPendingCommandsResponse(value);
      break;
    case 22:
      var value = new vehicle$events_pb.AcknowledgeVEPUpdatesByVIN;
      reader.readMessage(value,vehicle$events_pb.AcknowledgeVEPUpdatesByVIN.deserializeBinaryFromReader);
      msg.setAcknowledgeVepUpdatesByVin(value);
      break;
    case 23:
      var value = new protos_pb.AcknowledgeAssignedVehicles;
      reader.readMessage(value,protos_pb.AcknowledgeAssignedVehicles.deserializeBinaryFromReader);
      msg.setAcknowledgeAssignedVehicles(value);
      break;
    case 26:
      var value = new vehicle$events_pb.AcknowledgeDataChangeEvent;
      reader.readMessage(value,vehicle$events_pb.AcknowledgeDataChangeEvent.deserializeBinaryFromReader);
      msg.setAcknowledgeDataChangeEvent(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.ClientMessage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.ClientMessage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.ClientMessage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.ClientMessage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getTrackingId();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getUnsubscriberequest();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      protos_pb.UnsubscribeRequest.serializeBinaryToWriter
    );
  }
  f = message.getCommandrequest();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      vehicle$commands_pb.CommandRequest.serializeBinaryToWriter
    );
  }
  f = message.getTrackingEvent();
  if (f != null) {
    writer.writeMessage(
      4,
      f,
      vehicle$events_pb.TrackingEvent.serializeBinaryToWriter
    );
  }
  f = message.getPingInterval();
  if (f != null) {
    writer.writeMessage(
      6,
      f,
      vehicle$events_pb.ConfigurePingInterval.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeVepRequest();
  if (f != null) {
    writer.writeMessage(
      7,
      f,
      vehicle$events_pb.AcknowledgeVEPRequest.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeServiceStatusUpdatesByVin();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      service$activation_pb.AcknowledgeServiceStatusUpdatesByVIN.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeServiceStatusUpdate();
  if (f != null) {
    writer.writeMessage(
      13,
      f,
      service$activation_pb.AcknowledgeServiceStatusUpdate.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeUserDataUpdate();
  if (f != null) {
    writer.writeMessage(
      10,
      f,
      user$events_pb.AcknowledgeUserDataUpdate.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeUserPictureUpdate();
  if (f != null) {
    writer.writeMessage(
      11,
      f,
      user$events_pb.AcknowledgeUserPictureUpdate.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeUserPinUpdate();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      user$events_pb.AcknowledgeUserPINUpdate.serializeBinaryToWriter
    );
  }
  f = message.getUpdateUserJwtRequest();
  if (f != null) {
    writer.writeMessage(
      14,
      f,
      user$events_pb.UpdateUserJWTRequest.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeUserVehicleAuthChangedUpdate();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      user$events_pb.AcknowledgeUserVehicleAuthChangedUpdate.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeAbilityToGetVehicleMasterDataFromRestApi();
  if (f != null) {
    writer.writeMessage(
      16,
      f,
      user$events_pb.AcknowledgeAbilityToGetVehicleMasterDataFromRestAPI.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeVehicleUpdated();
  if (f != null) {
    writer.writeMessage(
      17,
      f,
      vehicle$events_pb.AcknowledgeVehicleUpdated.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgePreferredDealerChange();
  if (f != null) {
    writer.writeMessage(
      18,
      f,
      vehicle$events_pb.AcknowledgePreferredDealerChange.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeApptwinCommandStatusUpdateByVin();
  if (f != null) {
    writer.writeMessage(
      19,
      f,
      vehicleapi_pb.AcknowledgeAppTwinCommandStatusUpdatesByVIN.serializeBinaryToWriter
    );
  }
  f = message.getLogout();
  if (f != null) {
    writer.writeMessage(
      20,
      f,
      proto.proto.Logout.serializeBinaryToWriter
    );
  }
  f = message.getApptwinPendingCommandsResponse();
  if (f != null) {
    writer.writeMessage(
      21,
      f,
      vehicleapi_pb.AppTwinPendingCommandsResponse.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeVepUpdatesByVin();
  if (f != null) {
    writer.writeMessage(
      22,
      f,
      vehicle$events_pb.AcknowledgeVEPUpdatesByVIN.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeAssignedVehicles();
  if (f != null) {
    writer.writeMessage(
      23,
      f,
      protos_pb.AcknowledgeAssignedVehicles.serializeBinaryToWriter
    );
  }
  f = message.getAcknowledgeDataChangeEvent();
  if (f != null) {
    writer.writeMessage(
      26,
      f,
      vehicle$events_pb.AcknowledgeDataChangeEvent.serializeBinaryToWriter
    );
  }
};


/**
 * optional string tracking_id = 5;
 * @return {string}
 */
proto.proto.ClientMessage.prototype.getTrackingId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.setTrackingId = function(value) {
  return jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional UnsubscribeRequest unsubscribeRequest = 2;
 * @return {?proto.proto.UnsubscribeRequest}
 */
proto.proto.ClientMessage.prototype.getUnsubscriberequest = function() {
  return /** @type{?proto.proto.UnsubscribeRequest} */ (
    jspb.Message.getWrapperField(this, protos_pb.UnsubscribeRequest, 2));
};


/**
 * @param {?proto.proto.UnsubscribeRequest|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setUnsubscriberequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 2, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearUnsubscriberequest = function() {
  return this.setUnsubscriberequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasUnsubscriberequest = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional CommandRequest commandRequest = 3;
 * @return {?proto.proto.CommandRequest}
 */
proto.proto.ClientMessage.prototype.getCommandrequest = function() {
  return /** @type{?proto.proto.CommandRequest} */ (
    jspb.Message.getWrapperField(this, vehicle$commands_pb.CommandRequest, 3));
};


/**
 * @param {?proto.proto.CommandRequest|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setCommandrequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 3, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearCommandrequest = function() {
  return this.setCommandrequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasCommandrequest = function() {
  return jspb.Message.getField(this, 3) != null;
};


/**
 * optional TrackingEvent tracking_event = 4;
 * @return {?proto.proto.TrackingEvent}
 */
proto.proto.ClientMessage.prototype.getTrackingEvent = function() {
  return /** @type{?proto.proto.TrackingEvent} */ (
    jspb.Message.getWrapperField(this, vehicle$events_pb.TrackingEvent, 4));
};


/**
 * @param {?proto.proto.TrackingEvent|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setTrackingEvent = function(value) {
  return jspb.Message.setOneofWrapperField(this, 4, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearTrackingEvent = function() {
  return this.setTrackingEvent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasTrackingEvent = function() {
  return jspb.Message.getField(this, 4) != null;
};


/**
 * optional ConfigurePingInterval ping_interval = 6;
 * @return {?proto.proto.ConfigurePingInterval}
 */
proto.proto.ClientMessage.prototype.getPingInterval = function() {
  return /** @type{?proto.proto.ConfigurePingInterval} */ (
    jspb.Message.getWrapperField(this, vehicle$events_pb.ConfigurePingInterval, 6));
};


/**
 * @param {?proto.proto.ConfigurePingInterval|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setPingInterval = function(value) {
  return jspb.Message.setOneofWrapperField(this, 6, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearPingInterval = function() {
  return this.setPingInterval(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasPingInterval = function() {
  return jspb.Message.getField(this, 6) != null;
};


/**
 * optional AcknowledgeVEPRequest acknowledge_vep_request = 7;
 * @return {?proto.proto.AcknowledgeVEPRequest}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeVepRequest = function() {
  return /** @type{?proto.proto.AcknowledgeVEPRequest} */ (
    jspb.Message.getWrapperField(this, vehicle$events_pb.AcknowledgeVEPRequest, 7));
};


/**
 * @param {?proto.proto.AcknowledgeVEPRequest|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeVepRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 7, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeVepRequest = function() {
  return this.setAcknowledgeVepRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeVepRequest = function() {
  return jspb.Message.getField(this, 7) != null;
};


/**
 * optional AcknowledgeServiceStatusUpdatesByVIN acknowledge_service_status_updates_by_vin = 9;
 * @return {?proto.proto.AcknowledgeServiceStatusUpdatesByVIN}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeServiceStatusUpdatesByVin = function() {
  return /** @type{?proto.proto.AcknowledgeServiceStatusUpdatesByVIN} */ (
    jspb.Message.getWrapperField(this, service$activation_pb.AcknowledgeServiceStatusUpdatesByVIN, 9));
};


/**
 * @param {?proto.proto.AcknowledgeServiceStatusUpdatesByVIN|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeServiceStatusUpdatesByVin = function(value) {
  return jspb.Message.setOneofWrapperField(this, 9, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeServiceStatusUpdatesByVin = function() {
  return this.setAcknowledgeServiceStatusUpdatesByVin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeServiceStatusUpdatesByVin = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional AcknowledgeServiceStatusUpdate acknowledge_service_status_update = 13;
 * @return {?proto.proto.AcknowledgeServiceStatusUpdate}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeServiceStatusUpdate = function() {
  return /** @type{?proto.proto.AcknowledgeServiceStatusUpdate} */ (
    jspb.Message.getWrapperField(this, service$activation_pb.AcknowledgeServiceStatusUpdate, 13));
};


/**
 * @param {?proto.proto.AcknowledgeServiceStatusUpdate|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeServiceStatusUpdate = function(value) {
  return jspb.Message.setOneofWrapperField(this, 13, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeServiceStatusUpdate = function() {
  return this.setAcknowledgeServiceStatusUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeServiceStatusUpdate = function() {
  return jspb.Message.getField(this, 13) != null;
};


/**
 * optional AcknowledgeUserDataUpdate acknowledge_user_data_update = 10;
 * @return {?proto.proto.AcknowledgeUserDataUpdate}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeUserDataUpdate = function() {
  return /** @type{?proto.proto.AcknowledgeUserDataUpdate} */ (
    jspb.Message.getWrapperField(this, user$events_pb.AcknowledgeUserDataUpdate, 10));
};


/**
 * @param {?proto.proto.AcknowledgeUserDataUpdate|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeUserDataUpdate = function(value) {
  return jspb.Message.setOneofWrapperField(this, 10, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeUserDataUpdate = function() {
  return this.setAcknowledgeUserDataUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeUserDataUpdate = function() {
  return jspb.Message.getField(this, 10) != null;
};


/**
 * optional AcknowledgeUserPictureUpdate acknowledge_user_picture_update = 11;
 * @return {?proto.proto.AcknowledgeUserPictureUpdate}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeUserPictureUpdate = function() {
  return /** @type{?proto.proto.AcknowledgeUserPictureUpdate} */ (
    jspb.Message.getWrapperField(this, user$events_pb.AcknowledgeUserPictureUpdate, 11));
};


/**
 * @param {?proto.proto.AcknowledgeUserPictureUpdate|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeUserPictureUpdate = function(value) {
  return jspb.Message.setOneofWrapperField(this, 11, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeUserPictureUpdate = function() {
  return this.setAcknowledgeUserPictureUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeUserPictureUpdate = function() {
  return jspb.Message.getField(this, 11) != null;
};


/**
 * optional AcknowledgeUserPINUpdate acknowledge_user_pin_update = 12;
 * @return {?proto.proto.AcknowledgeUserPINUpdate}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeUserPinUpdate = function() {
  return /** @type{?proto.proto.AcknowledgeUserPINUpdate} */ (
    jspb.Message.getWrapperField(this, user$events_pb.AcknowledgeUserPINUpdate, 12));
};


/**
 * @param {?proto.proto.AcknowledgeUserPINUpdate|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeUserPinUpdate = function(value) {
  return jspb.Message.setOneofWrapperField(this, 12, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeUserPinUpdate = function() {
  return this.setAcknowledgeUserPinUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeUserPinUpdate = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * optional UpdateUserJWTRequest update_user_jwt_request = 14;
 * @return {?proto.proto.UpdateUserJWTRequest}
 */
proto.proto.ClientMessage.prototype.getUpdateUserJwtRequest = function() {
  return /** @type{?proto.proto.UpdateUserJWTRequest} */ (
    jspb.Message.getWrapperField(this, user$events_pb.UpdateUserJWTRequest, 14));
};


/**
 * @param {?proto.proto.UpdateUserJWTRequest|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setUpdateUserJwtRequest = function(value) {
  return jspb.Message.setOneofWrapperField(this, 14, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearUpdateUserJwtRequest = function() {
  return this.setUpdateUserJwtRequest(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasUpdateUserJwtRequest = function() {
  return jspb.Message.getField(this, 14) != null;
};


/**
 * optional AcknowledgeUserVehicleAuthChangedUpdate acknowledge_user_vehicle_auth_changed_update = 15;
 * @return {?proto.proto.AcknowledgeUserVehicleAuthChangedUpdate}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeUserVehicleAuthChangedUpdate = function() {
  return /** @type{?proto.proto.AcknowledgeUserVehicleAuthChangedUpdate} */ (
    jspb.Message.getWrapperField(this, user$events_pb.AcknowledgeUserVehicleAuthChangedUpdate, 15));
};


/**
 * @param {?proto.proto.AcknowledgeUserVehicleAuthChangedUpdate|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeUserVehicleAuthChangedUpdate = function(value) {
  return jspb.Message.setOneofWrapperField(this, 15, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeUserVehicleAuthChangedUpdate = function() {
  return this.setAcknowledgeUserVehicleAuthChangedUpdate(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeUserVehicleAuthChangedUpdate = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional AcknowledgeAbilityToGetVehicleMasterDataFromRestAPI acknowledge_ability_to_get_vehicle_master_data_from_rest_api = 16;
 * @return {?proto.proto.AcknowledgeAbilityToGetVehicleMasterDataFromRestAPI}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeAbilityToGetVehicleMasterDataFromRestApi = function() {
  return /** @type{?proto.proto.AcknowledgeAbilityToGetVehicleMasterDataFromRestAPI} */ (
    jspb.Message.getWrapperField(this, user$events_pb.AcknowledgeAbilityToGetVehicleMasterDataFromRestAPI, 16));
};


/**
 * @param {?proto.proto.AcknowledgeAbilityToGetVehicleMasterDataFromRestAPI|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeAbilityToGetVehicleMasterDataFromRestApi = function(value) {
  return jspb.Message.setOneofWrapperField(this, 16, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeAbilityToGetVehicleMasterDataFromRestApi = function() {
  return this.setAcknowledgeAbilityToGetVehicleMasterDataFromRestApi(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeAbilityToGetVehicleMasterDataFromRestApi = function() {
  return jspb.Message.getField(this, 16) != null;
};


/**
 * optional AcknowledgeVehicleUpdated acknowledge_vehicle_updated = 17;
 * @return {?proto.proto.AcknowledgeVehicleUpdated}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeVehicleUpdated = function() {
  return /** @type{?proto.proto.AcknowledgeVehicleUpdated} */ (
    jspb.Message.getWrapperField(this, vehicle$events_pb.AcknowledgeVehicleUpdated, 17));
};


/**
 * @param {?proto.proto.AcknowledgeVehicleUpdated|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeVehicleUpdated = function(value) {
  return jspb.Message.setOneofWrapperField(this, 17, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeVehicleUpdated = function() {
  return this.setAcknowledgeVehicleUpdated(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeVehicleUpdated = function() {
  return jspb.Message.getField(this, 17) != null;
};


/**
 * optional AcknowledgePreferredDealerChange acknowledge_preferred_dealer_change = 18;
 * @return {?proto.proto.AcknowledgePreferredDealerChange}
 */
proto.proto.ClientMessage.prototype.getAcknowledgePreferredDealerChange = function() {
  return /** @type{?proto.proto.AcknowledgePreferredDealerChange} */ (
    jspb.Message.getWrapperField(this, vehicle$events_pb.AcknowledgePreferredDealerChange, 18));
};


/**
 * @param {?proto.proto.AcknowledgePreferredDealerChange|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgePreferredDealerChange = function(value) {
  return jspb.Message.setOneofWrapperField(this, 18, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgePreferredDealerChange = function() {
  return this.setAcknowledgePreferredDealerChange(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgePreferredDealerChange = function() {
  return jspb.Message.getField(this, 18) != null;
};


/**
 * optional AcknowledgeAppTwinCommandStatusUpdatesByVIN acknowledge_apptwin_command_status_update_by_vin = 19;
 * @return {?proto.proto.AcknowledgeAppTwinCommandStatusUpdatesByVIN}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeApptwinCommandStatusUpdateByVin = function() {
  return /** @type{?proto.proto.AcknowledgeAppTwinCommandStatusUpdatesByVIN} */ (
    jspb.Message.getWrapperField(this, vehicleapi_pb.AcknowledgeAppTwinCommandStatusUpdatesByVIN, 19));
};


/**
 * @param {?proto.proto.AcknowledgeAppTwinCommandStatusUpdatesByVIN|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeApptwinCommandStatusUpdateByVin = function(value) {
  return jspb.Message.setOneofWrapperField(this, 19, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeApptwinCommandStatusUpdateByVin = function() {
  return this.setAcknowledgeApptwinCommandStatusUpdateByVin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeApptwinCommandStatusUpdateByVin = function() {
  return jspb.Message.getField(this, 19) != null;
};


/**
 * optional Logout logout = 20;
 * @return {?proto.proto.Logout}
 */
proto.proto.ClientMessage.prototype.getLogout = function() {
  return /** @type{?proto.proto.Logout} */ (
    jspb.Message.getWrapperField(this, proto.proto.Logout, 20));
};


/**
 * @param {?proto.proto.Logout|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setLogout = function(value) {
  return jspb.Message.setOneofWrapperField(this, 20, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearLogout = function() {
  return this.setLogout(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasLogout = function() {
  return jspb.Message.getField(this, 20) != null;
};


/**
 * optional AppTwinPendingCommandsResponse apptwin_pending_commands_response = 21;
 * @return {?proto.proto.AppTwinPendingCommandsResponse}
 */
proto.proto.ClientMessage.prototype.getApptwinPendingCommandsResponse = function() {
  return /** @type{?proto.proto.AppTwinPendingCommandsResponse} */ (
    jspb.Message.getWrapperField(this, vehicleapi_pb.AppTwinPendingCommandsResponse, 21));
};


/**
 * @param {?proto.proto.AppTwinPendingCommandsResponse|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setApptwinPendingCommandsResponse = function(value) {
  return jspb.Message.setOneofWrapperField(this, 21, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearApptwinPendingCommandsResponse = function() {
  return this.setApptwinPendingCommandsResponse(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasApptwinPendingCommandsResponse = function() {
  return jspb.Message.getField(this, 21) != null;
};


/**
 * optional AcknowledgeVEPUpdatesByVIN acknowledge_vep_updates_by_vin = 22;
 * @return {?proto.proto.AcknowledgeVEPUpdatesByVIN}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeVepUpdatesByVin = function() {
  return /** @type{?proto.proto.AcknowledgeVEPUpdatesByVIN} */ (
    jspb.Message.getWrapperField(this, vehicle$events_pb.AcknowledgeVEPUpdatesByVIN, 22));
};


/**
 * @param {?proto.proto.AcknowledgeVEPUpdatesByVIN|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeVepUpdatesByVin = function(value) {
  return jspb.Message.setOneofWrapperField(this, 22, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeVepUpdatesByVin = function() {
  return this.setAcknowledgeVepUpdatesByVin(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeVepUpdatesByVin = function() {
  return jspb.Message.getField(this, 22) != null;
};


/**
 * optional AcknowledgeAssignedVehicles acknowledge_assigned_vehicles = 23;
 * @return {?proto.proto.AcknowledgeAssignedVehicles}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeAssignedVehicles = function() {
  return /** @type{?proto.proto.AcknowledgeAssignedVehicles} */ (
    jspb.Message.getWrapperField(this, protos_pb.AcknowledgeAssignedVehicles, 23));
};


/**
 * @param {?proto.proto.AcknowledgeAssignedVehicles|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeAssignedVehicles = function(value) {
  return jspb.Message.setOneofWrapperField(this, 23, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeAssignedVehicles = function() {
  return this.setAcknowledgeAssignedVehicles(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeAssignedVehicles = function() {
  return jspb.Message.getField(this, 23) != null;
};


/**
 * optional AcknowledgeDataChangeEvent acknowledge_data_change_event = 26;
 * @return {?proto.proto.AcknowledgeDataChangeEvent}
 */
proto.proto.ClientMessage.prototype.getAcknowledgeDataChangeEvent = function() {
  return /** @type{?proto.proto.AcknowledgeDataChangeEvent} */ (
    jspb.Message.getWrapperField(this, vehicle$events_pb.AcknowledgeDataChangeEvent, 26));
};


/**
 * @param {?proto.proto.AcknowledgeDataChangeEvent|undefined} value
 * @return {!proto.proto.ClientMessage} returns this
*/
proto.proto.ClientMessage.prototype.setAcknowledgeDataChangeEvent = function(value) {
  return jspb.Message.setOneofWrapperField(this, 26, proto.proto.ClientMessage.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.proto.ClientMessage} returns this
 */
proto.proto.ClientMessage.prototype.clearAcknowledgeDataChangeEvent = function() {
  return this.setAcknowledgeDataChangeEvent(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.proto.ClientMessage.prototype.hasAcknowledgeDataChangeEvent = function() {
  return jspb.Message.getField(this, 26) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.Logout.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.Logout.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.Logout} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Logout.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.Logout}
 */
proto.proto.Logout.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.Logout;
  return proto.proto.Logout.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.Logout} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.Logout}
 */
proto.proto.Logout.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.Logout.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.Logout.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.Logout} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.Logout.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.proto);
