// source: eventpush.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var acp_pb = require('./acp_pb.js');
goog.object.extend(proto, acp_pb);
var gogo_pb = require('./gogo_pb.js');
goog.object.extend(proto, gogo_pb);
goog.exportSymbol('proto.proto.EventPushCommand', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.proto.EventPushCommand = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.proto.EventPushCommand.repeatedFields_, null);
};
goog.inherits(proto.proto.EventPushCommand, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.proto.EventPushCommand.displayName = 'proto.proto.EventPushCommand';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.proto.EventPushCommand.repeatedFields_ = [8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.proto.EventPushCommand.prototype.toObject = function(opt_includeInstance) {
  return proto.proto.EventPushCommand.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.proto.EventPushCommand} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.EventPushCommand.toObject = function(includeInstance, msg) {
  var f, obj = {
    vin: jspb.Message.getFieldWithDefault(msg, 1, ""),
    state: jspb.Message.getFieldWithDefault(msg, 2, 0),
    condition: jspb.Message.getFieldWithDefault(msg, 3, 0),
    type: jspb.Message.getFieldWithDefault(msg, 4, 0),
    processId: jspb.Message.getFieldWithDefault(msg, 5, 0),
    trackingId: jspb.Message.getFieldWithDefault(msg, 6, ""),
    correlationId: jspb.Message.getFieldWithDefault(msg, 7, ""),
    errorCodesList: (f = jspb.Message.getRepeatedField(msg, 8)) == null ? undefined : f,
    guid: jspb.Message.getFieldWithDefault(msg, 9, ""),
    timestampInS: jspb.Message.getFieldWithDefault(msg, 10, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.proto.EventPushCommand}
 */
proto.proto.EventPushCommand.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.proto.EventPushCommand;
  return proto.proto.EventPushCommand.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.proto.EventPushCommand} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.proto.EventPushCommand}
 */
proto.proto.EventPushCommand.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setVin(value);
      break;
    case 2:
      var value = /** @type {!proto.proto.VVA.CommandState} */ (reader.readEnum());
      msg.setState(value);
      break;
    case 3:
      var value = /** @type {!proto.proto.VVA.CommandCondition} */ (reader.readEnum());
      msg.setCondition(value);
      break;
    case 4:
      var value = /** @type {!proto.proto.ACP.CommandType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setProcessId(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setTrackingId(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.setCorrelationId(value);
      break;
    case 8:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedInt32() : [reader.readInt32()]);
      for (var i = 0; i < values.length; i++) {
        msg.addErrorCodes(values[i]);
      }
      break;
    case 9:
      var value = /** @type {string} */ (reader.readString());
      msg.setGuid(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setTimestampInS(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.proto.EventPushCommand.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.proto.EventPushCommand.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.proto.EventPushCommand} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.proto.EventPushCommand.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getVin();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getState();
  if (f !== 0.0) {
    writer.writeEnum(
      2,
      f
    );
  }
  f = message.getCondition();
  if (f !== 0.0) {
    writer.writeEnum(
      3,
      f
    );
  }
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getProcessId();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getTrackingId();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getCorrelationId();
  if (f.length > 0) {
    writer.writeString(
      7,
      f
    );
  }
  f = message.getErrorCodesList();
  if (f.length > 0) {
    writer.writePackedInt32(
      8,
      f
    );
  }
  f = message.getGuid();
  if (f.length > 0) {
    writer.writeString(
      9,
      f
    );
  }
  f = message.getTimestampInS();
  if (f !== 0) {
    writer.writeInt64(
      10,
      f
    );
  }
};


/**
 * optional string vin = 1;
 * @return {string}
 */
proto.proto.EventPushCommand.prototype.getVin = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.setVin = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional VVA.CommandState state = 2;
 * @return {!proto.proto.VVA.CommandState}
 */
proto.proto.EventPushCommand.prototype.getState = function() {
  return /** @type {!proto.proto.VVA.CommandState} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {!proto.proto.VVA.CommandState} value
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.setState = function(value) {
  return jspb.Message.setProto3EnumField(this, 2, value);
};


/**
 * optional VVA.CommandCondition condition = 3;
 * @return {!proto.proto.VVA.CommandCondition}
 */
proto.proto.EventPushCommand.prototype.getCondition = function() {
  return /** @type {!proto.proto.VVA.CommandCondition} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {!proto.proto.VVA.CommandCondition} value
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.setCondition = function(value) {
  return jspb.Message.setProto3EnumField(this, 3, value);
};


/**
 * optional ACP.CommandType type = 4;
 * @return {!proto.proto.ACP.CommandType}
 */
proto.proto.EventPushCommand.prototype.getType = function() {
  return /** @type {!proto.proto.ACP.CommandType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.proto.ACP.CommandType} value
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional int64 process_id = 5;
 * @return {number}
 */
proto.proto.EventPushCommand.prototype.getProcessId = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.setProcessId = function(value) {
  return jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional string tracking_id = 6;
 * @return {string}
 */
proto.proto.EventPushCommand.prototype.getTrackingId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.setTrackingId = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional string correlation_id = 7;
 * @return {string}
 */
proto.proto.EventPushCommand.prototype.getCorrelationId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 7, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.setCorrelationId = function(value) {
  return jspb.Message.setProto3StringField(this, 7, value);
};


/**
 * repeated int32 error_codes = 8;
 * @return {!Array<number>}
 */
proto.proto.EventPushCommand.prototype.getErrorCodesList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 8));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.setErrorCodesList = function(value) {
  return jspb.Message.setField(this, 8, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.addErrorCodes = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 8, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.clearErrorCodesList = function() {
  return this.setErrorCodesList([]);
};


/**
 * optional string guid = 9;
 * @return {string}
 */
proto.proto.EventPushCommand.prototype.getGuid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 9, ""));
};


/**
 * @param {string} value
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.setGuid = function(value) {
  return jspb.Message.setProto3StringField(this, 9, value);
};


/**
 * optional int64 timestamp_in_s = 10;
 * @return {number}
 */
proto.proto.EventPushCommand.prototype.getTimestampInS = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/**
 * @param {number} value
 * @return {!proto.proto.EventPushCommand} returns this
 */
proto.proto.EventPushCommand.prototype.setTimestampInS = function(value) {
  return jspb.Message.setProto3IntField(this, 10, value);
};


goog.object.extend(exports, proto.proto);
